# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  # don't support 2.6
  - 2.7
  # flask does not support python3 <3.3
  - 3.3
  - 3.4
  - 3.5
install: pip install -r requirements/dev.txt
script: py.test --cov-report= --cov=p101stat tests
after_success: coveralls
