"""empty message

Revision ID: 3ab570ed87dc
Revises: None
Create Date: 2016-01-12 14:00:46.022353

"""

# revision identifiers, used by Alembic.
revision = '3ab570ed87dc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name_kr', sa.String(length=32), nullable=False),
    sa.Column('first_name_en', sa.String(length=32), nullable=True),
    sa.Column('last_name_en', sa.String(length=32), nullable=True),
    sa.Column('agency', sa.String(length=256), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('vote_percentage', sa.Float(), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=False),
    sa.Column('is_vote_restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idx')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idols')
    ### end Alembic commands ###
