"""empty message

Revision ID: c25189ab2b31
Revises: d9e98cba5844
Create Date: 2016-01-14 20:30:10.723983

"""

# revision identifiers, used by Alembic.
revision = 'c25189ab2b31'
down_revision = 'd9e98cba5844'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idols', sa.Column('prev_rank', sa.Integer(), server_default=u'0', nullable=False))
    op.add_column('idols', sa.Column('prev_vote_percentage', sa.Float(), server_default=u'0.0', nullable=False))
    op.add_column('idols', sa.Column('rank', sa.Integer(), server_default=u'0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idols', 'rank')
    op.drop_column('idols', 'prev_vote_percentage')
    op.drop_column('idols', 'prev_rank')
    ### end Alembic commands ###
